[dependencies]
  soulsoft_asp_mvc = { path = "../soulsoft_asp_mvc"}
  soulsoft_asp_http = { path = "../soulsoft_asp_http"}
  soulsoft_asp_routing = { path = "../soulsoft_asp_routing"}
  soulsoft_asp_hosting = { path = "../soulsoft_asp_hosting"}
  soulsoft_security_claims = { path = "../soulsoft_security_claims"}
  soulsoft_identity_tokens = { path = "../soulsoft_identity_tokens"}
  soulsoft_identity_tokens_jwt = { path = "../soulsoft_identity_tokens_jwt"}
  soulsoft_asp_staticfiles = { path = "../soulsoft_asp_staticfiles"}
  soulsoft_asp_healthchecks = { path = "../soulsoft_asp_healthchecks"}
  soulsoft_asp_authorization = { path = "../soulsoft_asp_authorization"}
  soulsoft_asp_authentication = { path = "../soulsoft_asp_authentication"}
  soulsoft_extensions_hosting = { path = "../soulsoft_extensions_hosting"}
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}
  soulsoft_extensions_options = { path = "../soulsoft_extensions_options"}
  soulsoft_extensions_injection = { path = "../soulsoft_extensions_injection"}
  soulsoft_extensions_healthchecks = { path = "../soulsoft_extensions_healthchecks"}
  soulsoft_extensions_configuration = { path = "../soulsoft_extensions_configuration"}
  soulsoft_asp_authentication_jwtbearer = { path = "../soulsoft_asp_authentication_jwtbearer"}
[package]
  cjc-version = "0.60.5"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "soulsoft_asp"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]
