[package]
  cjc-version = "1.0.0"
  name = "soulsoft_web_authentication_jwtbearer"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  soulsoft_web_http = { path = "../soulsoft_web_http"}
  soulsoft_identity_claims = { path = "../soulsoft_identity_claims"}
  soulsoft_identity_tokens = { path = "../soulsoft_identity_tokens"}
  soulsoft_identity_tokens_jwt = { path = "../soulsoft_identity_tokens_jwt"}
  soulsoft_web_authentication = { path = "../soulsoft_web_authentication"}
  soulsoft_extensions_options = { path = "../soulsoft_extensions_options"}
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}
  soulsoft_identity_protocols = { path = "../soulsoft_identity_protocols"}
  soulsoft_extensions_injection = { path = "../soulsoft_extensions_injection"}
  soulsoft_identity_protocols_oidc = { path = "../soulsoft_identity_protocols_oidc"}

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]