
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "soulsoft_extensions_hosting"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
  
[dependencies]
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}
  soulsoft_extensions_options = { path = "../soulsoft_extensions_options"}
  soulsoft_extensions_injection = { path = "../soulsoft_extensions_injection"}
  soulsoft_extensions_configuration = { path = "../soulsoft_extensions_configuration"}
  soulsoft_extensions_logging_configuration = { path = "../soulsoft_extensions_logging_configuration"}  
