[package]
  cjc-version = "0.60.5"
  name = "soulsoft_asp_authentication_jwtbearer"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  soulsoft_security_claims = { path = "../soulsoft_security_claims"}
  soulsoft_security_tokens_jwt = { path = "../soulsoft_security_tokens_jwt"}
  soulsoft_asp_http = { path = "../soulsoft_asp_http"}
  soulsoft_asp_authentication = { path = "../soulsoft_asp_authentication"}
  soulsoft_extensions_options = { path = "../soulsoft_extensions_options"}
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]