[package]
  cjc-version = "1.0.0"
  name = "soulsoft_asp_authentication"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  soulsoft_asp_http = { path = "../soulsoft_asp_http"}
  soulsoft_security_claims = { path = "../soulsoft_security_claims"}
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}
  soulsoft_extensions_options = { path = "../soulsoft_extensions_options"}
  soulsoft_extensions_injection = { path = "../soulsoft_extensions_injection"}