[package]
  cjc-version = "0.60.5"
  name = "soulsoft_asp_authorization"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  soulsoft_asp_http = { git = "https://gitcode.com/soulsoft/soulsoft_asp_http.git", branch = "main"}
  soulsoft_asp_routing = { git = "https://gitcode.com/soulsoft/soulsoft_asp_routing.git", branch = "main"}
  soulsoft_security_claims = { git = "https://gitcode.com/soulsoft/soulsoft_security_claims.git", branch = "main"}
  soulsoft_extensions_options = { git = "https://gitcode.com/soulsoft/soulsoft_extensions_options.git", branch = "main"}
  soulsoft_extensions_injection = { git = "https://gitcode.com/soulsoft/soulsoft_extensions_injection.git", branch = "main"}
  # test
  soulsoft_asp_hosting = { git = "https://gitcode.com/soulsoft/soulsoft_asp_hosting.git", branch = "main"}
  soulsoft_asp_authentication = { git = "https://gitcode.com/soulsoft/soulsoft_asp_authentication.git", branch = "main"}
  soulsoft_extensions_logging = { git = "https://gitcode.com/soulsoft/soulsoft_extensions_logging.git", branch = "main"}

[target.x86_64-w64-mingw32]                                                     # 系统架构和 OS 信息
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["D:\\cangjiestdx\\windows_x86_64_llvm\\stdx\\dynamic\\stdx"] # stdx 路径根据实际情况配置
