[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "aspire_extensions_configuration"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}


[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]