
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "soulsoft_asp_hosting"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[dependencies]
  soulsoft_asp_http = { path = "../soulsoft_asp_http"}
  soulsoft_security_claims = { path = "../soulsoft_security_claims"}
  soulsoft_extensions_hosting = { path = "../soulsoft_extensions_hosting"}
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}
  soulsoft_extensions_options = { path = "../soulsoft_extensions_options"}
  soulsoft_extensions_injection = { path = "../soulsoft_extensions_injection"}
  soulsoft_extensions_configuration = { path = "../soulsoft_extensions_configuration"}
  soulsoft_extensions_logging_configuration = { path = "../soulsoft_extensions_logging_configuration"}

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]